# Generated by Django 5.0.6 on 2024-06-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_bookuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='image',
            field=models.ImageField(default='users/default.jpeg', upload_to='users/'),
        ),
    ]
