# Generated by Django 5.0.6 on 2024-06-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
