# Generated by Django 5.0.6 on 2024-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_bookuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuser',
            name='reward_point',
            field=models.IntegerField(default=0),
        ),
    ]
