# Generated by Django 5.0.6 on 2024-07-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_gift_stock'),
        ('user', '0008_bookuser_reward_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUserGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('point_cost', models.IntegerField()),
                ('book_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bookuser')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.gift')),
            ],
        ),
        migrations.AddField(
            model_name='bookuser',
            name='gifts',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_users', through='user.BookUserGift', to='gift.gift'),
        ),
    ]
