# Generated by Django 5.0.6 on 2024-07-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_bookusergift_bookuser_gifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuser',
            name='gifts',
        ),
    ]
