# Generated by Django 5.0.6 on 2024-08-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_bookuser_gifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
