# Generated by Django 5.0.6 on 2024-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reward_point',
            field=models.IntegerField(default=0),
        ),
    ]
