# Generated by Django 5.0.6 on 2024-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
